#!/usr/bin/env bash
# Apply the common application services plus the isolated local-chain overlay.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/localnet/.env"
if [[ ! -f "$ENV_FILE" ]]; then
    echo "Run localnet/prepare.sh first." >&2
    exit 1
fi
set -a
# This file is operator-controlled and generated by prepare.sh.
source "$ENV_FILE"
set +a
if [[ "$ENVIRONMENT" != localnet || "$NETUID" != 2 || "$BITTENSOR_NETWORK" != ws://subtensor:9944 ||
      "$HOST_WALLET_DIR" != "$REPO_ROOT/localnet/wallets" ||
      "$FACTORY_HORDE_DATA_ROOT" != "$REPO_ROOT/localnet/state/data" ]]; then
    echo "Localnet requires subnet 2, the local endpoint, and isolated localnet/ wallet and data paths." >&2
    exit 1
fi
if [[ -f "$REPO_ROOT/localnet/state/validator-image.id" ]]; then
    VALIDATOR_IMAGE="$(cat "$REPO_ROOT/localnet/state/validator-image.id")"
    export VALIDATOR_IMAGE
fi
exec docker compose --project-name factory-horde-localnet --env-file "$ENV_FILE" \
    -f "$REPO_ROOT/envs/deployed/docker-compose.yml" -f "$REPO_ROOT/localnet/compose.yml" "$@"
